Дипломный проект
arcyandex/java-explore-with-me pull request #4
Opened 2022-11-05 15:57 UTC by arcyandex

2022-11-06 10:35 UTC, eugene-lenkevich requested changes
Привет, Алексей, спасибо за PR

Первым делом поздравляю тебя с тем, что ты дошел до дипломной работы, ты крут без вариантов :)

Далее, 
вообще, в целом, все отлично, но наша цель в том, чтобы сделать красоту в этом проекте, все таки диплом, вдруг по нему будут оценивать навыки. Я оставил кучку коментариев, будут вопросы, задавай в слаке, не стесняйся, немножко допилить осталось :)

Главное поправь формат дат и все мелочи

Удачи!

2022-11-06 10:35 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/repository/EventRepository.java
> +    List<Event> getEventsWithParameters(@Param("search") String textSearch,
getEventsWithParameters

Мне акажется что названиме метода немного вводит в заблуждение. Можно подумать что помимо событий вытаскиваются и еще какие то "параметры", если же имеется в виду что посик ведется по ращным полям так это и так ясно из сигнатуры метода (масло масляное). Если это так, то может назвать просто getEvents, метод ниже аналогично :)

2022-11-06 10:35 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        if (users == null || users.size() == 0) {
Это конечно очень не оптимально вытаскивать всех пользователей  и категории чтобы передать их снова в запрос и понятно почему так сделано - запрос потому что с динамическим набором параметров :)

Если хватит времени разобраться то посмотри, пожалуйста, query DSL

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.extensions.querydsl

![image](https://user-images.githubusercontent.com/94845100/200165038-6eb1ed5b-f578-44d6-ae8e-8fd46682a592.png)

Если получится то будет супер, возможно вот этой статьи достаточно чтобы разобраться

https://sysout.ru/ispolzovanie-querydslpredicateexecutor/

2022-11-06 10:35 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        if (update.getAnnotation() != null) event.setAnnotation(update.getAnnotation());
Немного синтаксического сахара. Это модно записать вот так\

Optional.ofNullable(update.getAnnotation()).ifPresent(event::setAnnotation)

2022-11-06 10:35 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventPublicServiceImpl.java
> +    @Transactional
Тут же не изменяются данные, @Transactional избыточен, только лишние накладные расходы. Он нуден для тех методов где происходит изменение данных (insert, update или delete)

2022-11-06 10:35 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/statistics/StatClient.java
> +public class StatClient extends BaseClient {
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2022-11-06 10:35 UTC, eugene-lenkevich commented on stats/src/main/java/ru/practicum/ewmstat/service/StatServiceImpl.java
> +    public void saveStatInfo(EndpointHit endpointHit) {
Вот над сохранением и аналогичными методами и можно поставить @Transactional :)

2022-11-06 23:48 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/category/service/CategoryAdminServiceImpl.java
> +        Category categoryDuplicate = categoryRepository.findByNameIsContainingIgnoreCase(categoryDto.getName());
Сделал

2022-11-06 23:49 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/category/service/CategoryAdminServiceImpl.java
> +        categoryRepository.findById(catId).orElseThrow(() -> new NotFoundException("Категория не найдена"));
Заменил там, где результат findById не требовалось записывать в переменную

2022-11-06 23:49 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +    public CompilationServiceImpl(CompilationRepository compilationRepository, CompilationMapper compilationMapper) {
Готово

2022-11-06 23:50 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/event/dto/AdminUpdateEventRequest.java
> +    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE, pattern = "yyyy-MM-dd HH:mm:ss")
Сделал через отдельный класс с аннотацией Configuration и настройкой в yml

2022-11-06 23:50 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/event/repository/EventRepository.java
> +    List<Event> getEventsWithParameters(@Param("search") String textSearch,
Переименовал

2022-11-06 23:51 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        if (update.getAnnotation() != null) event.setAnnotation(update.getAnnotation());
Сделал

2022-11-06 23:51 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventPublicServiceImpl.java
> +    @Transactional
Убрал

2022-11-06 23:51 UTC, arcyandex commented on stats/src/main/java/ru/practicum/ewmstat/service/StatServiceImpl.java
> +    public void saveStatInfo(EndpointHit endpointHit) {
Добавил

2022-11-06 23:58 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/statistics/StatClient.java
> +public class StatClient extends BaseClient {
Вот тут улучшил только отчасти - вместо константы стал брать значение URL из настройки в yml-файле плюс подчистил код baseClient от неиспользуемых методов. Но конструктор оставил в самом клиенте.

Причина в том, что я из этого же клиента отдельным методом отправляю статистику hit'ов и для этого сделал наследование от baseClient, где лежит нужная реализация метода POST. Если наследование убрать, остаемся без этой реализации и надо переписывать обработку hit'ов в статистике полностью.

2022-11-07 00:00 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        if (users == null || users.size() == 0) {
Вот тут нормальную реализацию сделать не получилось. Принцип работы с предикатами в целом понял, но на практике докрутить под мою реализацию не удалось - боюсь из всех дедлайнов выбиться и не доделать дополнительную фичу вовремя.

2022-11-07 04:48 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/event/service/EventAdminServiceImpl.java
> +        if (users == null || users.size() == 0) {
И не надо, все верно  :)

2022-11-07 04:48 UTC, eugene-lenkevich commented on ewm/src/main/java/ru/practicum/ewm/statistics/StatClient.java
> +public class StatClient extends BaseClient {
Ок, не критично

2022-11-07 04:54 UTC, eugene-lenkevich approved these changes
Спасибо за исправлдения,

ага, самые важные мометы ты исправил, наверное заметил как много кода удалось таким образом просто удалить без потери функциональности, а то что на чтото не хватило времени - вполне себе рабочая ситуация, именно так часто и бывает :)

Теперь все отлично, спасибо :)

Не забудь в задачу подложить актуальный архив с исходниками в задачу, вроде просят

2022-11-07 06:04 UTC, merged