Фича, комментарии к событиям
arcyandex/java-explore-with-me pull request #5
Opened 2022-11-08 12:40 UTC by arcyandex

2022-11-08 17:17 UTC, PorotikovSergey requested changes

2022-11-08 17:17 UTC, PorotikovSergey commented on ewm/src/main/java/ru/practicum/ewm/comment/model/Comment.java
> +    @JoinColumn(name = "user_id", referencedColumnName = "id")
Иногда полезно указать для гибернейта возможно ли полю быть nullable или нет

2022-11-08 17:17 UTC, PorotikovSergey commented on ewm/src/main/java/ru/practicum/ewm/comment/model/Comment.java
> +    private Integer id;
Для больших сервисов лучше брать для id long вместо int. Пока нам это неважно, но в будущем может уберечь нас от проблем.

2022-11-08 17:17 UTC, PorotikovSergey commented on ewm/src/main/resources/schema.sql
> +    text_com varchar,
Мог бы посоветовать указывать количество символов для varchar, а то неродивые юзеры смогут в комментарии целую войну и мир вставить. Целая страница текста на листе а4 - это примерно 1800 символов. Было бы неплохо установить рамки в этом пределе.

2022-11-08 21:50 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/comment/dto/NewCommentDto.java
> +    private String text;
Добавил

2022-11-08 21:50 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/comment/model/Comment.java
> +    @JoinColumn(name = "user_id", referencedColumnName = "id")
Добавил

2022-11-08 21:50 UTC, PorotikovSergey commented
Только теперь нужно под новопришедшие тесты починить основную часть

2022-11-08 21:51 UTC, arcyandex commented on ewm/src/main/java/ru/practicum/ewm/comment/model/Comment.java
> +    private Integer id;
Пока оставил как было, иначе валятся тесты по событиям, но в целом 2 с лишним миллиарда комментариев хватит надолго :)

2022-11-08 21:51 UTC, arcyandex commented on ewm/src/main/resources/schema.sql
> +    text_com varchar,
Добавил

2022-11-10 17:54 UTC, PorotikovSergey approved these changes

2022-11-13 09:40 UTC, merged